export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Create Survey Form
export const CREATE_SURVEY_FORM = "CREATE_SURVEY_FORM";
export const CREATE_NEW_FORM_SUCCESS = "CREATE_NEW_FORM_SUCCESS";
export const GET_ALL_TOOL_PROCESS = "GET_ALL_TOOL_PROCESS";

//View / Update Survey Form
export const GET_SURVEY_FORM = "GET_SURVEY_FORM";
export const GET_ALL_SURVEY_FORM = "GET_ALL_SURVEY_FORM";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const CLEAR_UPDATING_FORM = "CLEAR_UPDATING_FORM";

export const PREVIEW_SURVEY_FORM = "PREVIEW_SURVEY_FORM"
export const CLEAR_PREVIEW_FORM = "CLEAR_PREVIEW_FORM"

export const DELETE_SURVEY_FORM = "DELETE_SURVEY_FORM";

export const GET_LOGIN_DETAILS = "GET_LOGIN_DETAILS";
export const REGISTER_NEW_EMPLOYEE = "REGISTER_NEW_EMPLOYEE";

export const GET_ALL_ROLES = "GET_ALL_ROLES";

export const GET_EMPLOYEES_FOR_MANAGER_SUCCESS = "GET_EMPLOYEES_FOR_MANAGER_SUCCESS"

//Evaluation
export const CREATE_EVALUATION_SUCCESS = "CREATE_EVALUATION_SUCCESS";
export const GET_EVALUATION_SUCCESS = "GET_EVALUATION_SUCCESS"
export const UPDATE_EVALUATION_SUCCESS = "UPDATE_EVALUATION_SUCCESS";
export const CLEAR_UPDATING_EVALUATION = "CLEAR_UPDATING_EVALUATION"
export const ASSIGN_EVALUATION_SUCCESS = "ASSIGN_EVALUATION_SUCCESS"

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_ASSIGNED_EVALUATIONS_SUCCESS = "GET_ASSIGNED_EVALUATIONS_SUCCESS";



