export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Create Survey Form
export const CREATE_SURVEY_FORM = "CREATE_SURVEY_FORM";
export const CREATE_NEW_FORM_SUCCESS = "CREATE_NEW_FORM_SUCCESS";
export const GET_ALL_TOOL_PROCESS = "GET_ALL_TOOL_PROCESS";

//View / Update Survey Form
export const GET_SURVEY_FORM = "GET_SURVEY_FORM";
export const UPDATE_FORM_SUCCESS = "UPDATE_FORM_SUCCESS";
export const CLEAR_UPDATING_FORM = "CLEAR_UPDATING_FORM";
